# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
# permalink: /:title.html
paginate: 5
plugins_dir: [jekyll-paginate]
port: 3000
safe: true
gems: [jekyll-paginate]

# edit here to achieve your personal greatness
url: https://nightwhistler.github.io
# baseurl: /
title: Alex Kuiper
author: Alex Kuiper
description: Personal blog and resume for Alex Kuiper
avatar: profile.png
email: alex@nightwhistler.net
github: nightwhistler
twitter: nightwhistler
linkedin: alkuiper
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
